package com.example.aretech.ui.activities.menu.print.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class PrintData(
    val date: String,
    val create_date:String,
    val clientCode: String,
    val clientName: String,
    val docId: String,
    val docSeri: String,
    val docSira: String,
    val ficheNo: String,
    val docType: String,
    val docName:String,
    val amount: String,
    val discount: String,
    val gross_total: String,
    val vat:String,
    val desc: String,
    val projeCode: String,
    val projeName: String,
    val mesmerCode: String,
    val mesmerName: String,
    val debt: String,
    val driver: String,
    val saleReturnStatus: String,
    val printStatus:Boolean,
    val slsCode: String,
    val slsName: String,
    val whCode: String,
    val whName: String,
    val out_whCode: String = "",
    val out_whName: String = "",
    val cashName: String,
    val cashCode: String,
    val bankName: String,
    val bankCode: String,
    val payTypeCode: String,
    val payTypeName: String,
    val special1Code: String,
    val special1Name: String,
    val special2Code: String,
    val special2Name: String,
    val special3Code: String,
    val special3Name: String,
) : Parcelable