package com.example.aretech.global.constants.Constants

object Constants {
    const val PARENT = 0
    const val CHILD = 1
    const val LOCATION_PERMISSION_REQUEST_CODE_FOREGROUND = 1001
    const val LOCATION_PERMISSION_REQUEST_CODE_BACKGROUND = 1004
    const val POST_NOTIFICATION_PERMISSION_REQUEST_CODE = 1002
    const val ALARM_SCHEDULE_PERMISSION_REQUEST_CODE = 1003
    const val ACCESS_FINE_LOCATION = "android.permission.ACCESS_FINE_LOCATION"
    const val  SHOW_GPS_ENABLED_OR_NOT_CHANNEL = "SHOW_GPS_ENABLED_OR_NOT_CHANNEL"
    const val INTERNET_LOCKED_OR_UNLOCKED_WORKER_DATA = "SHOW_GPS_ENABLED_OR_NOT_CHANNEL"
    const val BATTERY_LEVEL = "BATTERY_LEVEL"
    const val GPS_LOCKED_WORKER = "SHOW_GPS_LOCKED_WORKER"
    const val INTERNET_LOCKED_WORKER = "SHOW_INTERNET_LOCKED_WORKER"
    const val RESTART_SERVICE = "RESTART_SERVICE"
    const val STOP_SERVICE = "STOP_SERVICE"
    const val REFRESH_DATA = "REFRESH_DATA"
    const val STOP_APPLICATION = "STOP_APPLICATION"
    const val REFRESH_DATA_EMPTY = "REFRESH_DATA_EMPTY"
    const val IGNORE_BATTERY_OPTIMIZATION_ACTION_CHANGED = "android.os.action.POWER_SAVE_WHITELIST_CHANGED"
    const val TIME_LEFT_VISIT_STATUS_VIEW = 50
    var BASE_URL = "http://github.sabuhi"
    const val FRAGMENT_KEY_BARCODE = "FRAGMENT_KEY"
    const val FRAGMENT_RESULT_BARCODE_CODE = "FRAGMENT_RESULT_BARCODE_CODE"
    const val DEFAULT_DURATION_DAY_COLOR = "#000000"
}